### ISSUE TITLE
Problems installing plugin with Unreal 4.26.2, and also with 5

### ISSUE THREAD

**Issue by javismiles** [TouchDesigner/TouchEngine-UE4#101]
good day, we are transitioning to UE5, and the plugin only seems to work with UE4, when do you think there will be a version that works with UE5?

Also even when trying plugin in UE4 latest version I get error:
The following modules are missing or built with a different engine version:
touchengine
touchengineeditor

thank you for any help

**Comment by jetXS** [comment]
All solved on Derivative forum, closing
