### ISSUE TITLE
TouchEngine Component "dynamic" properties should be keyframable in Sequencer

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#102]
Following: https://docs.unrealengine.com/4.27/en-US/AnimatingObjects/Sequencer/Overview/Keyframing/

It is not possible to add / edit any of the "dynamic" properties from a TouchEngine Component to the sequencer.

We should research if we can enable this for the end-users. If not possible at the moment because of software architecture, what could be changed to enable this.

**Comment by ddthejj** [comment]
Added an update to the readme in 20d76d5acd1b5a5b715dce65eeb215115e866045 with a workaround to this since the dynamic variables can't be used in the level sequencer directly
