### ISSUE TITLE
"Mega"-node in Blueprint

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#103]
Currently the individual inputs/outputs coming in/out of TD are done via individual blueprint nodes that write/read from them. Epic suggested that we also create a dynamic ‘mega-node’ that has all the inputs and outputs visible on a single node.

**Comment by ddthejj** [comment]
Added in 6a026b3bc5858cd7335994c31e9b55329c6e4080

**Comment by jetXS** [comment]
Closing for now, to experiment with and see if the workflow makes sense in new sample.
