### ISSUE TITLE
Drag n dropping of .tox to assets browser / Recognize .tox files as valid UE assets

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#104]
Would create Actor with TouchEngine Component and all parameters and i/o read writes needed to act as “pass-thru” that can then be built around / tweaked. Most probably should be done after the Mega Node feature and rely on this new mega node.

**Comment by jetXS** [comment]
Ok, maybe I should have given more details on the flow for this one, here is what I was thinking of:

- Drag n drop a .tox to the Content Browser, in our example, we'll go with UESample01_EnginePerform.tox
- After drag n drop occurs, a new BP "TouchEngineActor" is created, just like if I had created it by doing a right click -> Create Blueprint Class and looked for TouchEngineActor

![image](https://user-images.githubusercontent.com/10253645/142276392-5d88d829-f737-475a-a738-16c237e57e61.png)

- Now double click the TouchEngineActor that just got created with the name "TE_Actor_UESample01_EnginePerform" (automatic name)

- Everything still looks the same as if a user had just created a TouchEngineActor, but the file path is properly filled within the TouchEngine Component of the Actor BP -> Details panel -> Tox File section -> Tox File Path property

I like the idea of .tox files becoming .uassets, but I don't like hiding the path to the tox in another object. I'd rather have it just create a TouchEngine Actor as described above.

**Comment by ddthejj** [comment]
so there's a few problems with that functionality - 
1 is that that's not how a user would expect that to function, I would think an Unreal user would expect an asset file to drag into their implementation of the component
2 is that I'm not sure how a user would have 2 different objects that use the same tox file in the same folder - at least, they couldn't drag n drop 2 different versions, since UE4 will try to reimport a file it's already imported

**Comment by jetXS** [comment]
Please revert the change with the .uasset, it is unnecessary at the moment with it just holding a path...

If this .uasset could hold serialized data for all parameters / inputs / outputs... maybe, why not. But with the current UX, I don't see the purpose really... 😅

After our talk with Epic, is more exploration possible to see if my original idea of building a base TouchEngine Actor BP referencing the .tox file something we can look into ?

Thanks

**Comment by jetXS** [comment]
Hey @ddthejj 

Let's revert the drag n drop for now, where there is just the path to .tox file in a .uassets, then we can put back this issue on hold.

Thanks

**Comment by ddthejj** [comment]
reverted in 116dd42a9a9b7296e9f908c09444c941043b1e9b
