### ISSUE TITLE
Error when debugger is attached and quitting Unreal editor

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#109]
Could be just an Unreal issue and non related to the Plugin. 

![image](https://user-images.githubusercontent.com/10253645/142492353-94d01029-ec70-440c-bf78-977a0e9762d0.png)

Not easy to reproduce... Don't spend much time looking into it and close if it looks like some random debugger or Engine issue.

**Comment by ddthejj** [comment]
I haven't been able to repro this issue - if it happens again, please take a screenshot of the callstack so I can debug this more acurately.

**Comment by jetXS** [comment]
Couldn't reproduce
