### ISSUE TITLE
Crash while reloading a .tox without a valid license

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#110]
![image](https://user-images.githubusercontent.com/10253645/142512771-73ac8530-f1f4-4e04-9c78-cc03495168ab.png)

It just happened after waiting a long while...

Clicking reload .tox of UESample04 BP, after a play session and leaving play mode.

Could be related to https://github.com/TouchDesigner/TouchEngine-UE4/issues/108

**Comment by ddthejj** [comment]
I haven't been able to repro this issue - if it happens again, please take a screenshot of the callstack so I can debug this more accurately.
This may also have been fixed along with #108

**Comment by jetXS** [comment]
Cannot reproduce, closing.
