### ISSUE TITLE
Cannot build project without editor

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#112]
Through VS, when config doesn't have editor:
![image](https://user-images.githubusercontent.com/10253645/143044670-343db796-1a7b-4fcc-ba4c-adfb2f7502ba.png)

**Comment by ddthejj** [comment]
Fixed in f634815229ddc5beeb014429d743a2c94d2a2fe7

**Comment by jetXS** [comment]
Tested and confirmed as fixed, thanks
