### ISSUE TITLE
Crash when unloading .tox

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#114]
![crash While Unloading Tox](https://user-images.githubusercontent.com/10253645/145112773-ad1c3ad0-9784-432b-94b3-73692e38ebe1.png)

I was loading samples 1-5 together, then tried to unload them except number 3.

It crashed while unloading the first, I think.

Doesn't seem easy to reproduce though 😬

**Comment by ddthejj** [comment]
Hopefully fixed in 19c75c82bfa85ab43bd42f3d60239c4a5080edbe - could not repro
