### ISSUE TITLE
Crash when unloading sample 09

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#115]
![crash While Unloading Tox 09](https://user-images.githubusercontent.com/10253645/145114919-958a2875-2cc0-4464-b248-b75d03643f22.png)

When unloading sample 09

I can't tell if this is related but I had noticed some odd data in the texture viewer of the sample 09, like in the attached screenshot.

Changing TouchEngine Components in the details panel and going back to it would change it also, like if it was garbage data or something.

![image](https://user-images.githubusercontent.com/10253645/145115373-2187e98a-e638-4c84-838a-8d1e9c30b952.png)

**Comment by jetXS** [comment]
Unloading and reloading didn't crash, but the data being displayed is different

![image](https://user-images.githubusercontent.com/10253645/145115523-9327d769-09d5-40f4-8f93-aaaa644d0748.png)

**Comment by ddthejj** [comment]
Unfortunately there's not enough information (callstack, what code was crashed on) to debug this issue further - I haven't been able to repro the issues.

**Comment by jetXS** [comment]
Closing for now.
