### ISSUE TITLE
DirectX 12 Support

### ISSUE THREAD

**Issue by HerrDrFink** [TouchDesigner/TouchEngine-UE4#118]
Do you plan a release for the DirectX 12 support?
I know it's listed in the known issues.
I would like to use it with Unreal Engine 5 and RayTracing.
The Plugin works well in UE Version 5.0.1 after recompiling it automatically.
**Thank you for the good work!**

**Comment by jetXS** [comment]
Hey @HerrDrFink - apologies for the delay. This is on our roadmap but no ETA for now.

Best,
Michel

**Comment by jetXS** [comment]
Support is nearly completed in the UE5.0-Dev and UE5.1-Dev branches. Follow this repository for an official release soon.
