### ISSUE TITLE
Issue with Onloading textures in UE5

### ISSUE THREAD

**Issue by Batname** [TouchDesigner/TouchEngine-UE4#121]
![image](https://user-images.githubusercontent.com/6189196/174496654-691cf889-c15f-4d25-a789-751db155c2aa.png)

The crash is happening after trying to disable UESample2.

Steps to reproduce.

1. Package the game in the Development build
2. Start the game
3. Enable UESample 2
4. Disable UESample 2

When you disable that is automatically crashes

**Comment by RVillani** [comment]
I can't reproduce it with TD build 2022.25370 installed in the system.
Assuming the plugin uses the dlls inside its ThirdParty folder, the installed version shouldn't matter.
Unless I'm misunderstanding something.

Edit: What I meant (and forgot to say) is I don't think the installed version has to do with it working for me. I have done some YWIU fixes too, but I also don't think those would've fixed it.

**Comment by RVillani** [comment]
This issue should now be fixed. It was caused by cleaning up textures in the game thread, causing a race condition with operations happening on the render thread.
