### ISSUE TITLE
Unable to load TouchEngine plugin

### ISSUE THREAD

**Issue by phillpas** [TouchDesigner/TouchEngine-UE4#126]
I have been successfully using TouchEngine-UE 1.1.0 in an UE5.1 project on a Windows 10 machine for the past several weeks. I just built a new computer and install Windows 11, along with UE 5.1, TouchDesigner, and TouchEngine. Unfortunately I am now unable to use TouchEngine, even when running the TouchEngineUESamp project. While the project is able to build and run, when UE5.1 loads, I see the error message below. Additionally, I am unable to successfully load any of the tox files. 

![image](https://user-images.githubusercontent.com/3999900/211456986-7da11053-7411-4c3d-bf29-d287ae98bcf2.png).

System Info:
Windows 11
Unreal Engine 5.1
TouchDesigner 2022.31030
TouchEngine-UE 1.1.0

**Comment by bangnoise** [comment]
Oops, that's not a very helpful error message. What TouchDesigner license is installed on the machine?

**Comment by phillpas** [comment]
I have a TouchDesigner Commercial licence

**Comment by bangnoise** [comment]
What GPU's installed on the machine? Can you launch TouchDesigner successfully?

**Comment by phillpas** [comment]
I'm currently using an RTX 2080 TI. TouchDesigner runs successfully. Again, this issue popped up after running TouchEngine on a newly built PC (using the same GPU).

**Comment by bangnoise** [comment]
Thanks - we're looking into this. We fixed one possible cause of the lost error message on the UE5.1-Dev branch - could you try building that and let us know if you see a more detailed error?

**Comment by phillpas** [comment]
I just tried using UE5.1-Dev and get the following error:

"TouchEngine error - Handle type TED3DHandleTypeD3D12ResourceNT is not supported by this TouchEngine instance"

**Comment by bangnoise** [comment]
Thanks. Is there an integrated GPU on the system too?

**Comment by bangnoise** [comment]
...and is the Nvidia driver the latest available?

**Comment by phillpas** [comment]
Yes, I actually just upgraded my GPU this weekend and am seeing the same issue. It is using the latest Nvidia driver

**Comment by phillpas** [comment]
Sorry, I think I misinterpreted your question. I do have an i9-13900k which has Intel® UHD Graphics 770. But my dedicated GPU is an Nvidia card.

**Comment by bangnoise** [comment]
Thanks - we're still trying to recreate this here, so it's helpful to know the exact setup. It's possible something is going wrong with GPU selection and the Intel GPU is being used incorrectly - we will investigate that scenario.

**Comment by bangnoise** [comment]
If you're keen to get things working in the meantime and don't need to use the Intel GPU you could try disabling it in BIOS if that's an option.

**Comment by phillpas** [comment]
I just disabled integrated graphics in the BIOS and I'm still getting the same error

**Comment by phillpas** [comment]
Here is the (partial) DxDiag file:

[diag.txt](https://github.com/TouchDesigner/TouchEngine-UE/files/10453067/diag.txt)

**Comment by phillpas** [comment]
I was able to find a solution to this issue. I had 2 versions of TD installed on my computer, one of them was a 2021 version. I read in the TouchEngine-Windows readme "By default the most recently installed version of TouchDesigner will be used." I must have installed the 2021 version after the latest 2022 version. After uninstalling the 2021 version of TouchDesigner, everything is working as expected in TouchEngine-Unreal and I no longer get the error.

**Comment by phillpas** [comment]
I was able to find a solution to this issue. I had 2 versions of TD installed on my computer, one of them was a 2021 version. I read in the TouchEngine-Windows readme "By default the most recently installed version of TouchDesigner will be used." I must have installed the 2021 version after the latest 2022 version. After uninstalling the 2021 version of TouchDesigner, everything is working as expected in TouchEngine-Unreal and I no longer get the error.

**Comment by bangnoise** [comment]
Ah! Thanks for the update. We'll see if we can make the reporting around this clearer.

If you want to work with two versions of TouchDesigner installed, you can place a link or Windows Explorer shortcut to the installation you want to use next to the .tox file you're loading and name it TouchEngine.
