### ISSUE TITLE
Problem with a TOP  texture in Niagara Sample Texture

### ISSUE THREAD

**Issue by kefon** [TouchDesigner/TouchEngine-UE4#129]
Hello there, 
First of course, thanks a lot for your hardwork, the plugin is great!
(using TouchEngine For UE 5.1 latest release)

I'm currently trying to use two TOP textures (32bits RGBA) to drive the positions and velocity of the particles in a Niagara system. So far everything is working as expected. The particles follow the positions from the TOP POS and I use my TOP VEL to calculate the orientation of the particles according to their velocity. Each texture is a 124x124px 32bits RGBA.

The problem is I noticed some weird movements/positions, and after a lot of testing I thought it comes from a pixel format problem. In Niagara I'm using the Sample Texture module to get the positions of each particles (1 pixel = 1 particles with RGB acting as XYZ). To be sure that the problem doesn't come from Niagara, I created a static texture in Touch pixel values within a -500/500 range, and saved it as a .EXR. When using it, all the particles are at the right place (setting the imported texture as **RGBA 32f + Filter = Nearest**). 

After more testing I identified the problem I think:
 **The Texture coming from TouchEngine TOP doesn't have its "Filter" set as "Nearest" in Unreal.**

Can you confirm?
Any idea on how to change that in BP after the "GetTouchEngineOutput" or "OnToxLoaded" events?

Thanks in advance for your help!

**Comment by jetXS** [comment]
Followed up via the Derivative forum and logged internally in our tracker, closing this issue.

https://forum.derivative.ca/t/touchengine-for-ue-5-1-problem-with-a-top-texture-in-niagara-sample-texture/349288/4
