### ISSUE TITLE
TDAbleton component is not working

### ISSUE THREAD

**Issue by vivimage** [TouchDesigner/TouchEngine-UE4#131]
Edited the UESample_CHOP_01_Read file. 
![image](https://github.com/TouchDesigner/TouchEngine-UE/assets/18232879/fb616fc9-1efc-40db-a4f0-56443f30fe61)

Inside the Touch Designer everything is working fine. The ableton is connecting without the issue and I am able to map the parameter. 

But inside the Unreal when I load this tox file, I receive errors. 
No TouchEngine CHOP Data is transferred
![image](https://github.com/TouchDesigner/TouchEngine-UE/assets/18232879/be3c32cf-4412-4086-8489-87c1b1346449)
 
 
 I want to connect ableton to unreal engine through the TDAbleton in Touch Designer

**Comment by vivimage** [comment]
![image](https://github.com/TouchDesigner/TouchEngine-UE/assets/18232879/3897b847-fb76-4e1f-bf46-b9f27bf89f8d)
You can see in this chop output that device is not connected.

**Comment by vivimage** [comment]
`LogClass: Error: BoolProperty FTouchEngineDATData::bIsRowMajor is not initialized properly. Module:TouchEngine File:Public/Engine/TouchVariables.h
LogAutomationTest: Error: UObject.Class AttemptToFindUninitializedScriptStructMembers will be marked as failing due to errors being logged
LogAutomationTest: Error: LogClass: BoolProperty FTouchEngineDATData::bIsRowMajor is not initialized properly. Module:TouchEngine File:Public/Engine/TouchVariables.h
LogTouchEngineVulkanRHI: Error: Failed to load Vulkan Windows functions.`

Errors in the output log. Not sure If this is connected

**Comment by vivimage** [comment]
Tried with the latest version on UE5.2-Dev branch. Also not working, unfortunately

**Comment by jetXS** [comment]
Closing this issue as it is being addressed in the forum: https://forum.derivative.ca/t/touchengine-for-ue-5-2-problem-with-tdableton-package/372850/5
