### ISSUE TITLE
Error on Packaging 

### ISSUE THREAD

**Issue by jeebius** [TouchDesigner/TouchEngine-UE4#132]
Hi, I get the errors when I try to package for windows on unreal 5.3.1 and using TouchEngine 1.3.2. Any ideas how to resolve this?

TouchEngineDynamicVariableStructVersion.cpp.obj : error LNK2005: "class FCustomVersionRegistration GRegisterRemoteControlCustomVersion" (?GRegisterRemoteControlCustomVersion@@3VFCustomVersionRegistration@@A) already defined in Module.RemoteControl.4.cpp.obj
Creating library E:\Projects\TR_InteractiveRock\TR_InteractiveRock\Binaries\Win64\TR_InteractiveRock.lib and object E:\Projects\TR_InteractiveRock\TR_InteractiveRock\Binaries\Win64\TR_InteractiveRock.exp E:\Projects\TR_InteractiveRock\TR_InteractiveRock\Binaries\Win64\TR_InteractiveRock.exe : fatal error LNK1169: one or more multiply defined symbols found

**Comment by jetXS** [comment]
Hello @jeebius 

Thanks for the report.

A new release is now available fixing this issue.

Plugin v1.3.3.

You can pull the latest changes or get the release package.

Best,
M

**Comment by jeebius** [comment]
Thank you, It's working great!

**Comment by dichbg** [comment]
Unreal engine updated to 5.3.2 Two days ago, I downloaded the plugin just now, it works in editor, but packaging failed.
Is the only way to install unreal engine 5.3.1 from source?

**Comment by jetXS** [comment]
Hi @dichbg 

I just gave it a test and I cannot reproduce. It did package fine and run as expected when launching the exe on my end.

Can you give more details about your specific installation ?

Can you share the packaging log and where it failed?

Are you doing a project from scratch ? Did you try the samples project? Are you using other plugins ?

Thanks,
M

**Comment by dichbg** [comment]
Hello.

Thanks for the reply.

This is the packaging log:
[Log.txt](https://github.com/TouchDesigner/TouchEngine-UE/files/13316138/Log.txt)

I am not using other plugins.

I have started a project from scratch, on the open world level.

The UE installation is default.
I have Visual Studio 2022
The default project without the plugin packages.
Once I load the tox it fails.

The tox tha I'm trying to load is a 256x256 red solid with an out top.

**Comment by jetXS** [comment]
Hello @dichbg 

I've spent more time trying to reproduce and I'm unfortunately still unable to reproduce the issue. I started a new project from scratch to be on par with your project.

A developer will look into the log nonetheless. Thanks for sharing that.

I am thinking that it might be caused by some caching.

You are not recompiling the solution from VS right?

Could you please go to your project folder and, when applicable, remove the selected folders:
![image](https://github.com/TouchDesigner/TouchEngine-UE/assets/10253645/32c25fbb-410e-4f92-bca0-cc20ca33eae9)

In the Plugins folder, remove the intermediate folder:
![image](https://github.com/TouchDesigner/TouchEngine-UE/assets/10253645/2faa3bbf-9597-495b-a98e-12541f999995)

Double-click your .uproject, you should see a dialog stating that the project needs to be compiled.

Does it start the solution as expected?

Now, in Unreal, can you package the solution? Which config are you selecting to package? Shipping ?

**Comment by dichbg** [comment]
Hello

I am sorry.
I tried the above, I am still unable to package the project.

Is there a specific packaging guide when using the plugin? That I may have missed?
I am packaging from unreal, I am not compiling from VS.

Also I am using a blueprint project.

One more thing that can probably be a clue:
When I try to use the quick launch
![image](https://github.com/TouchDesigner/TouchEngine-UE/assets/29871226/1785fd80-25a1-4cd4-9ab5-328e4dcd37e2)

I get this error:
![image](https://github.com/TouchDesigner/TouchEngine-UE/assets/29871226/2aeaf819-6c40-4e8b-93b8-e4bcb4c29c8d)

However, the module is present in the plugins folder.

I replaced the plugin, deleted the above mentioned folders, and tried to launch again.
The error still persists.

**Comment by dichbg** [comment]
P.S. I have no problem building the Samples project :/

**Comment by dichbg** [comment]
P.S.

I deleted the default open world level, and added a new basic map.
Packaging was successful, but the plugin does not package with the project.

I get this error when I try to run the .exe file.
![image](https://github.com/TouchDesigner/TouchEngine-UE/assets/29871226/1fec28c1-4f3f-438f-9ed7-8c327c478571)

**Comment by dichbg** [comment]
P.S. 
Started a new project from scratch again, Selected the  film and video empty template.
Using the default level, I imported the

I successfully managed to package the project with the plugin, and run it.

**Comment by dichbg** [comment]
P.S.
To double check and try to reproduce, I created another project again, -> Games -> Blank -> Raytracing: ON.\
Map is open world default map.
The project cooks, packages, but does not run.
(Touch Engine Vulkan RHI missing message)

Here is the output log:
[Log.txt](https://github.com/TouchDesigner/TouchEngine-UE/files/13335549/Log.txt)

**Comment by jetXS** [comment]
Hi @dichbg 

> Is there a specific packaging guide when using the plugin? That I may have missed.

There is nothing too specific. Only Windows is supported and DX12 or Vulkan RHIs.
Package configurations, in your case likely Shipping, should all be covered.

> I have no problem building the Samples project :/

Probably something specific with the project you pick.

> Packaging was successful, but the plugin does not package with the project.

Not too sure what you mean by "the plugin does not package with the project".
It did package with the project if you get that error you mentioned.

>  Selected the film and video empty template.
> I successfully managed to package the project with the plugin, and run it.

Ok that's good to know.

> The project cooks, packages, but does not run.
> BUILD SUCCESSFUL

There are no errors in the log you shared. I will try this configuration though.

What are the specs of the computer you are building the project with and attempting to run the packaged project from?

I'll get back to you in a bit.

**Comment by dichbg** [comment]
CPU: Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz   3.60 GHz
Ram: 64.0 GB
GPU: Nvidia RTX A4000
OS: Windows 10 Pro
Version: 22H2
OS Build: 19045.3570

**Comment by jetXS** [comment]
Hi @dichbg 

After more testing, it seems that I can reproduce the issue, only in the Blank Open World project and only when RTX is enabled.

I had no issue with RTX enabled in the case of the Virtual Production project.

I am reporting this issue to our developer to look into it further.

Best,
M

**Comment by dichbg** [comment]
@jetXS Thank you.

It seems that I have the same isolated problem.
I also don't have any problem with the VP project and Raytracing.

Thanks for your support.

**Comment by jetXS** [comment]
Hey @dichbg - the latest release of the plugin, v1.3.4 should fix this rare issue encountered with the RTX Open World template.

Best,
M
