### ISSUE TITLE
1.3.3. Packaging failed, on 5.3.2

### ISSUE THREAD

**Issue by dichbg** [TouchDesigner/TouchEngine-UE4#133]
I know the release is for unreal engine 5.3.1, the hotfix was released 3 days ago, but 2 days ago they updated the engine to 5.3.2.
I downloaded the plugin just now, it works in editor, but packaging failed.
The 5.3.1 version is no longer available in the epic games launcher, is the only way to install from source ?

**Comment by jetXS** [comment]
That'd be the only solution I have in mind for the time being.

But let's fix your issue and get a new release if necessary so that you don't have to compile from source.

Just pointing out here that debugging is occuring in issue number #132 

Closing this issue to avoid duplicates.
