### ISSUE TITLE
Plugins > Touchdesigner folder empty?

### ISSUE THREAD

**Issue by AlysterVodka** [TouchDesigner/TouchEngine-UE4#135]
On running the project, it reports the TouchEngine plugin missing. downloading the TouchEngine folder separately from the repository and putting it in the plugin folder manually results in a 'built with another engine' message. Didn't manage to rebuild so far.

**Comment by jetXS** [comment]
Hi @AlysterVodka 

Sorry for the delay and for the issues.

This kind of issue can sometimes be caused by caching.

Can you confirm that you tried the latest version of the plugin in the Release page ? 

You cloned the main branch here and testing with UE5.3.2 ?

**Comment by AlysterVodka** [comment]
Hi, thanks for the reply

I have tested with UE 5.3.2 - I downloaded a ZIP from the main branch, however the folder of the plugin was empty on downloading, I navigated to the folder manually and downloaded the next available version, and implemented it manually locally. Potentially there is a discrepancy there? I saw an earlier comment saying as well that the folder was empty. I think it must have to do with this, what do you think, how can I proceed?

Thanks, Alyster


========================


STUDIO VODKA



Esther de Bruijn // Alyster

www.alyster.vodka<http://www.alyster.vodka/>

+31 6 11 41 38 80

________________________________

**Comment by jetXS** [comment]
You mean you downloaded a .zip from the following: https://github.com/TouchDesigner/TouchEngine-UE-Samples ?

This would not include the plugin folder as automated .zip files from Github don't include submodules, which is what the Plugin is.

Follow instructions as to how to properly get started here. https://github.com/TouchDesigner/TouchEngine-UE-Samples/blob/UE5.3-Release/docs/getting-started.md

You should either do a recursive clone, as explained, or download the zip files from the release pages of the repositories.
