### ISSUE TITLE
Missing Modules Error

### ISSUE THREAD

**Issue by digitalrainkr** [TouchDesigner/TouchEngine-UE4#136]
Hey, I just downloaded the UE 4.2 Plugin. Added it to the Plugins folder like explained in the Installation guide. Reopened the UE project and Turned the TouchEngine Plugin on. After Restarting I get the following Error Message:
![캡처](https://github.com/TouchDesigner/TouchEngine-UE/assets/137489387/b905a20d-5ea4-46b4-bb67-305e8987e823)

Rebuilding fails. 
![캡처](https://github.com/TouchDesigner/TouchEngine-UE/assets/137489387/0754b7d8-0cd5-4a51-94d5-ee4c8eddac6f)

Im working on a Windows PC with Intel Core i7 and NVIDIA GeForce RTX 4070 Ti. 
The UE Project contains one simple level with some Niagara Particles. No other Plugins are in use.

**Comment by jetXS** [comment]
Hi @digitalrainkr 

> UE 4.2 Plugin

Is there a typo here ? What version are you referring to?

What is the version of Unreal you are using ? What is the version of the plugin ?

Just looking at this message briefly, it looks like you need to recompile the project with Unreal build tools and you might be missing some dependencies.

Look at this section here: https://github.com/TouchDesigner/TouchEngine-UE/blob/UE5.4-Release/docs/FAQ.md#i-have-placed-the-plugin-in-the-plugin-folder-but-my-project-doesnt-start-anymore

Thank you for your time,

Best,
Michel

**Comment by digitalrainkr** [comment]
Hey @jetXS 

Sorry, Yes I made a Typo I meant 5.4. I am using UE 5.4 aswell. 

I realized its because of another Plugin I was testing. When the other Plugin is active the TouchEngine Plugin needs to compile from scratch.

**Comment by jetXS** [comment]
Got it, thanks.

**Comment by digitalrainkr** [comment]
Actually small update. Tried installing the 5.4 Plugin in a new UE 5.4 Project File without any other plugins installed and it still tells me to "Rebuild from source". I will be sticking to the 5.3 Plugin for now.

**Comment by jetXS** [comment]
Hi Caroline,

See following link
https://github.com/TouchDesigner/TouchEngine-UE/blob/UE5.4-Release/docs/FAQ.md#i-have-placed-the-plugin-in-the-plugin-folder-but-my-project-doesnt-start-anymore

Best,
Michel
