### ISSUE TITLE
Use a TouchEngine instance as a buffer when first loading the plugin to handle non-runtime details panel

### ISSUE THREAD

**Issue by mbechard** [TouchDesigner/TouchEngine-UE4#30]

**Comment by jetXS** [comment]
Updated title to make more sense with latest TouchEngine lib updates from https://github.com/TouchDesigner/TouchEngine-Windows/commit/72b64ba54ab09fe648d58fd2fef3ddd6355b3840

The idea would be to always have a TouchEngine Instance laying around for editor mode / not at runtime. As soon as we are at runtime or in a shipping build, "Load on Begin Play" should have priority.

**Comment by ddthejj** [comment]
Added in b7798c28d51bbcee204d6cbff409bb7124943c20
This looks to be a huge improvement for load times (in the details panel)

**Comment by jetXS** [comment]
Great improvement indeed, thanks.

Can we have a bit more details about the architecture ? I can't tell looking at the process manager if an instance is always laying around ready to be used as a buffer or something ? Or do we actually have mutliple instances laying around, one per TouchEngine Component in UE ? 

Please update plugin documentation and Cpp API documentation if / where necessary :) Can close this task once done.

Thanks !

**Comment by ddthejj** [comment]
I couldn't find anywhere to update the documentation (it's not at all necessary to know how it works behind the scenes, and no current documentation mentions the old way TouchEngine instances were loaded)
Currently there's an instance that's been initialized but not started lying around in the Subsystem that loads Tox files one by one if the game is not running to get the information into the details panel. I'm not 100% sure how this will show up in the task manager, but there should only ever be one TouchEngine instance loaded when the game is not running.
