### ISSUE TITLE
TOP: Inconsistencies with texture resolution and pixel format

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#83]
From forum post: https://forum.derivative.ca/t/touchengine-plugin-for-unreal-engine-beta-release/190764/20?u=jetxs

[computeshader.zip](https://github.com/TouchDesigner/TouchEngine-UE4/files/6755034/computeshader.zip)

Tested on my end with EnginePerform blueprint and SimpleTexture blueprint being tweaked.

I thought at first that it could have to do with the pixel format being set to 16-bit but changing to 8-bit didn't solve the issue.

Note, this is what we should see in UE:
![image](https://user-images.githubusercontent.com/10253645/124285764-4352d000-db1c-11eb-81f2-57f48753d6ce.png)

I then tested with a simple noise, and the results are odd based on resolution.

When noise is set to 128 x 128:

![image](https://user-images.githubusercontent.com/10253645/124286193-acd2de80-db1c-11eb-9b5b-8357f4b224a5.png)

While TD / Engine COMP is outputting

![image](https://user-images.githubusercontent.com/10253645/124286458-f8858800-db1c-11eb-9290-8f411e4cccab.png)

The only way to get the proper noise texture is to have it set to be 1024x1024 (512x512 is failing as well)

**Comment by bangnoise** [comment]
Confirmed output matches from the .tox directly and the .tox in Engine COMP at 128x128, 512x512, 1024x1024, so this doesn't initially seem like a problem in TouchEngine.

**Comment by ddthejj** [comment]
Fixed in b7f680d23fab9fc09d2369994bf2ae91e618b57c

**Comment by jetXS** [comment]
tested and confirmed as fixed, thanks
