### ISSUE TITLE
Improve logging when .tox are failing to loads

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#88]
We need more details, if at all possible, on why a .tox is failing to load.

**Comment by ddthejj** [comment]
The tox loading failures are mostly coming straight from TD - the ones I'm outputting are just about as verbose as I can make them.
More specifics on what's not verbose enough would be helpful

**Comment by ddthejj** [comment]
Added a bit of extra verbosity in db76096e803aad64a650cbe43c75fb74035befe3
