### ISSUE TITLE
Support for Unicode characters in Plugin

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#92]
TouchEngine supports Unicode characters, they should therefore be handled properly in the plugin

Example texts to try:

```
The Arabic alphabet (Arabic: الْأَبْجَدِيَّة الْعَرَبِيَّة‎, al-abjadīyah l-ʿarabīyah or الْحُرُوف الْعَرَبِيَّة, al-ḥurūf l-ʿarabīyah, IPA: [ʔalʔabd͡ʒadiːjaʰ lʕarabiːjaʰ])
```

```
表意文字, hyōui moji 和製漢字, wasei kanji; also known as “country’s kanji” 国字, kokuji
```

https://forum.derivative.ca/t/touch-engine-plugin-for-ue4-arabic-text-in-dats/211467

**Comment by ddthejj** [comment]
Added in 1367eba0bb84823fd5b0c269bf38972563ebd1bf

**Comment by jetXS** [comment]
fails to display on my end, am I missing something or an issue need to be opened for the samples project to be updated ?

![image](https://user-images.githubusercontent.com/10253645/139961473-fdf6d9ca-0660-459b-8264-3feeb9cc3e03.png)

**Comment by ddthejj** [comment]
So the problem here is that the default font doesn't support unicode characters as far as I can tell, I'll double check

**Comment by ddthejj** [comment]
![image](https://user-images.githubusercontent.com/29811612/140102850-c6868369-f1cb-42b1-b114-71354b60e0bb.png)
So this is a problem with this font - you'll need to use one that supports whatever language you're using

**Comment by jetXS** [comment]
I'll update the samples project with a font that covers this case then. Thanks.
