### ISSUE TITLE
Plugin doesn't run in UE4.27

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#96]
![image](https://user-images.githubusercontent.com/10253645/134673173-8e39d939-efc4-4293-bec0-1a5c12457f20.png)

From user https://forum.derivative.ca/t/unreal-engine-4-27-crash-with-plugin/216358?u=jetxs

Upgrade should be planned https://github.com/TouchDesigner/TouchEngine-UE4/issues/94

**Comment by ddthejj** [comment]
Fixed in c7f773a1422df86164d33fca7e6fc4ba899839ce

**Comment by jetXS** [comment]
Continue in #94 for other issues that show up due to 4.27
