### ISSUE TITLE
At runtime, updating from the details panel a UE property should update TouchEngine matching parameters right away

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#97]
Replace in your project that .tox which is a very simple twist. The parameter RGBA should update the background color of the texture that we are already using.

When loading that in an Engine from within TouchDesigner, using an Engine COMP, it does work as expected.

In UE, updating manually the property from the details panel doesn't do anything.
[UESample01_EnginePerform.zip](https://github.com/TouchDesigner/TouchEngine-UE4/files/7313547/UESample01_EnginePerform.zip)

**Comment by ddthejj** [comment]
Fixed in 80e8f800b4f6cd7e0ba1208fcea2cbc4bcbba734

**Comment by jetXS** [comment]
Tested and confirmed as fixed, thanks
