### ISSUE TITLE
Adding .tox path to TouchEngine Component is triggering a crash

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#98]
While testing latest update, in vanilla Vritual Production project, UE 4.27.1

I created a new TouchEngine Actor

Edited blueprint -> TouchEngine Component

In details panel of Blueprint editor, I started typing a path ( `Tox/ ` ) and then changed focus to go to my explorer to try and copy paste my .tox name.

This triggered a crash, I think because of the wrong path at first...

![image](https://user-images.githubusercontent.com/10253645/138461319-9feb14b6-173c-46bb-ac31-b00c82a68d31.png)

**Comment by ddthejj** [comment]
Managed to repro in latest, in progress

**Comment by ddthejj** [comment]
Fixed in ded5cb659b9a6eb5ef60d1de56bb1a5594c844e7

**Comment by jetXS** [comment]
Tested and confirmed as fixed.
