### ISSUE TITLE
Compile and run full shipping version w/o Editor but w/ Plugin and TE Actors

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4#99]
Using samples project. Making sure we can compile and run a full shipping version ready for production w/o Editor.

TBD further for build machine/setup.

**Comment by ddthejj** [comment]
we're currently crashing when trying to make shipping builds, working on this now

**Comment by ddthejj** [comment]
Fixed in e90b224d4889b92ffb965026eb692e415b807fa6

**Comment by jetXS** [comment]
Tested and confirmed as fixed
